server:
  port: 3004

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lqs
    url: jdbc:mysql://localhost:3306/mall_pms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false # 关闭thymeleaf缓存
# redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最晓空闲连接
        min-idle: 3
    # 连接超时时间（毫秒）
    password:
    timeout: 5000
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 缓存过期时间，毫秒
      # key-prefix: CACHE_ # 如果配了就用这个作为我前缀，如果没配置，就用  缓存分区名::key   缓存分区名::作为前缀
      use-key-prefix: false # 如果设置为true，就使用前缀，如果为false，直接不用前缀
      cache-null-values: true # 是否缓存空值，解决缓存穿透

mybatis-plus:
  mapper-locations:  classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0 # 逻辑删除
      logic-not-delete-value: 1 # 逻辑没删除
  configuration:
     map-underscore-to-camel-case: true


