# redis配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最晓空闲连接
        min-idle: 3
    # 连接超时时间（毫秒）
    password:
    timeout: 5000